import { createContext, useContext, useMemo, useState } from 'react'

export const SCHEMES = [
  { id: 'default', label: 'Default' },
  { id: 'gruvbox', label: 'Gruvbox' },
  { id: 'oneDark', label: 'One Dark' },
  { id: 'dracula', label: 'Dracula' },
  { id: 'tokyoNight', label: 'Tokyo Night' },
  { id: 'nord', label: 'Nord' },
]

const PALETTES = {
  default: {
    dark: {
      bg: '#121212',
      bgElevated: '#181818',
      bgInput: '#242424',
      bgChip: '#242424',
      border: '#282828',
      text: '#FFFFFF',
      textMuted: '#B3B3B3',
      accent: '#1DB954',
      accentText: '#000000',
      playButton: '#FFFFFF',
      playIcon: '#000000',
      progressTrack: '#4D4D4D',
      progressFill: '#FFFFFF',
      artwork: '#282828',
      artworkIcon: '#B3B3B3',
      statusBarStyle: 'light-content',
    },
    light: {
      bg: '#FFFFFF',
      bgElevated: '#F2F2F7',
      bgInput: '#EFEFF4',
      bgChip: '#EFEFF4',
      border: '#E5E5EA',
      text: '#000000',
      textMuted: '#6E6E73',
      accent: '#1DB954',
      accentText: '#FFFFFF',
      playButton: '#000000',
      playIcon: '#FFFFFF',
      progressTrack: '#D1D1D6',
      progressFill: '#000000',
      artwork: '#E5E5EA',
      artworkIcon: '#8E8E93',
      statusBarStyle: 'dark-content',
    },
  },
  gruvbox: {
    dark: {
      bg: '#282828',
      bgElevated: '#32302f',
      bgInput: '#3c3836',
      bgChip: '#3c3836',
      border: '#504945',
      text: '#ebdbb2',
      textMuted: '#a89984',
      accent: '#d65d0e',
      accentText: '#282828',
      playButton: '#ebdbb2',
      playIcon: '#282828',
      progressTrack: '#504945',
      progressFill: '#fabd2f',
      artwork: '#3c3836',
      artworkIcon: '#a89984',
      statusBarStyle: 'light-content',
    },
    light: {
      bg: '#fbf1c7',
      bgElevated: '#f2e5bc',
      bgInput: '#ebdbb2',
      bgChip: '#ebdbb2',
      border: '#d5c4a1',
      text: '#3c3836',
      textMuted: '#7c6f64',
      accent: '#af3a03',
      accentText: '#fbf1c7',
      playButton: '#3c3836',
      playIcon: '#fbf1c7',
      progressTrack: '#d5c4a1',
      progressFill: '#b57614',
      artwork: '#ebdbb2',
      artworkIcon: '#7c6f64',
      statusBarStyle: 'dark-content',
    },
  },
  oneDark: {
    dark: {
      bg: '#282c34',
      bgElevated: '#21252b',
      bgInput: '#3a3f4b',
      bgChip: '#3a3f4b',
      border: '#181a1f',
      text: '#abb2bf',
      textMuted: '#5c6370',
      accent: '#61afef',
      accentText: '#282c34',
      playButton: '#abb2bf',
      playIcon: '#282c34',
      progressTrack: '#3a3f4b',
      progressFill: '#61afef',
      artwork: '#3a3f4b',
      artworkIcon: '#5c6370',
      statusBarStyle: 'light-content',
    },
    light: {
      bg: '#fafafa',
      bgElevated: '#f0f0f1',
      bgInput: '#eaeaeb',
      bgChip: '#eaeaeb',
      border: '#d4d4d5',
      text: '#383a42',
      textMuted: '#a0a1a7',
      accent: '#4078f2',
      accentText: '#fafafa',
      playButton: '#383a42',
      playIcon: '#fafafa',
      progressTrack: '#d4d4d5',
      progressFill: '#4078f2',
      artwork: '#eaeaeb',
      artworkIcon: '#a0a1a7',
      statusBarStyle: 'dark-content',
    },
  },
  dracula: {
    dark: {
      bg: '#282a36',
      bgElevated: '#21222c',
      bgInput: '#44475a',
      bgChip: '#44475a',
      border: '#44475a',
      text: '#f8f8f2',
      textMuted: '#6272a4',
      accent: '#bd93f9',
      accentText: '#282a36',
      playButton: '#f8f8f2',
      playIcon: '#282a36',
      progressTrack: '#44475a',
      progressFill: '#ff79c6',
      artwork: '#44475a',
      artworkIcon: '#6272a4',
      statusBarStyle: 'light-content',
    },
    light: {
      bg: '#282a36',
      bgElevated: '#21222c',
      bgInput: '#44475a',
      bgChip: '#44475a',
      border: '#44475a',
      text: '#f8f8f2',
      textMuted: '#6272a4',
      accent: '#bd93f9',
      accentText: '#282a36',
      playButton: '#f8f8f2',
      playIcon: '#282a36',
      progressTrack: '#44475a',
      progressFill: '#ff79c6',
      artwork: '#44475a',
      artworkIcon: '#6272a4',
      statusBarStyle: 'light-content',
    },
  },
  tokyoNight: {
    dark: {
      bg: '#1a1b26',
      bgElevated: '#16161e',
      bgInput: '#24283b',
      bgChip: '#24283b',
      border: '#2f334d',
      text: '#c0caf5',
      textMuted: '#565f89',
      accent: '#7aa2f7',
      accentText: '#1a1b26',
      playButton: '#c0caf5',
      playIcon: '#1a1b26',
      progressTrack: '#2f334d',
      progressFill: '#7aa2f7',
      artwork: '#24283b',
      artworkIcon: '#565f89',
      statusBarStyle: 'light-content',
    },
    light: {
      bg: '#d5d6db',
      bgElevated: '#cbccd1',
      bgInput: '#c8c9cf',
      bgChip: '#c8c9cf',
      border: '#9da2a8',
      text: '#343b58',
      textMuted: '#6c6e75',
      accent: '#34548a',
      accentText: '#d5d6db',
      playButton: '#343b58',
      playIcon: '#d5d6db',
      progressTrack: '#9da2a8',
      progressFill: '#34548a',
      artwork: '#c8c9cf',
      artworkIcon: '#6c6e75',
      statusBarStyle: 'dark-content',
    },
  },
  nord: {
    dark: {
      bg: '#2e3440',
      bgElevated: '#3b4252',
      bgInput: '#434c5e',
      bgChip: '#434c5e',
      border: '#4c566a',
      text: '#eceff4',
      textMuted: '#81a1c1',
      accent: '#88c0d0',
      accentText: '#2e3440',
      playButton: '#eceff4',
      playIcon: '#2e3440',
      progressTrack: '#4c566a',
      progressFill: '#88c0d0',
      artwork: '#434c5e',
      artworkIcon: '#81a1c1',
      statusBarStyle: 'light-content',
    },
    light: {
      bg: '#eceff4',
      bgElevated: '#e5e9f0',
      bgInput: '#d8dee9',
      bgChip: '#d8dee9',
      border: '#a5abb6',
      text: '#2e3440',
      textMuted: '#4c566a',
      accent: '#5e81ac',
      accentText: '#eceff4',
      playButton: '#2e3440',
      playIcon: '#eceff4',
      progressTrack: '#a5abb6',
      progressFill: '#5e81ac',
      artwork: '#d8dee9',
      artworkIcon: '#4c566a',
      statusBarStyle: 'dark-content',
    },
  },
}

export function getSchemePalette(scheme, mode) {
  return PALETTES[scheme]?.[mode] || PALETTES.default.dark
}

const ThemeContext = createContext(null)

export function ThemeProvider({ children }) {
  const [mode, setMode] = useState('dark')
  const [scheme, setScheme] = useState('default')

  const value = useMemo(() => {
    const palette = PALETTES[scheme]?.[mode] || PALETTES.default.dark
    return {
      mode,
      scheme,
      palette,
      setMode,
      setScheme,
      toggleMode: () => setMode((m) => (m === 'dark' ? 'light' : 'dark')),
    }
  }, [mode, scheme])

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>
}

export function useTheme() {
  const ctx = useContext(ThemeContext)
  if (!ctx) throw new Error('useTheme must be used inside ThemeProvider')
  return ctx
}
